name = "GrandGameOfLife"
uuid = "307dbbc8-3393-4c29-a84a-08bd80db9f14"
authors = ["Andrey Oskin"]
version = "0.2.0"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
